import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <h1 className={styles.title}>Welcome to our demo blog!</h1>
      <p>
        You can find more articles on the{' '}
        <Link href='/blog'>
        <a>blog articles page</a>
        </Link>
      </p>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
